export const APP_SET_PLATFORM = 'APP_SET_PLATFORM';

export const UI_OPEN_NEW_BOOKMARK_DIALOG = 'UI_OPEN_NEW_BOOKMARK_DIALOG';

export const FILE_SET_META_DATA = 'FILE_SET_META_DATA';
export const FILE_SET_SAVED = 'FILE_SET_SAVED';
export const FILE_SET_LOADED = 'FILE_SET_LOADED';

export const PROJECT_SET_PROJECT = 'PROJECT_SET_PROJECT';
export const PROJECT_SET_PROJECT_INFO = 'PROJECT_SET_PROJECT_INFO';
export const PROJECT_DELETE_IMAGE = 'PROJECT_DELETE_IMAGE';
export const PROJECT_SET_BOOKMARKS = 'PROJECT_SET_BOOKMARKS';
export const PROJECT_ADD_BOOKMARK = 'PROJECT_ADD_BOOKMARK';
