export const APP_SET_PLATFORM = 'APP_SET_PLATFORM';

export const UI_SET_PREFERENCES = 'UI_SET_PREFERENCES';
export const UI_SET_SIDEBAR_WIDTH = 'UI_SET_SIDEBAR_WIDTH';
export const UI_OPEN_EDIT_TASK_DIALOG = 'UI_OPEN_EDIT_TASK_DIALOG';
export const UI_OPEN_EDIT_BOOKMARK_DIALOG = 'UI_OPEN_EDIT_BOOKMARK_DIALOG';
export const UI_SET_TASKS_SORTING_OPTIONS = 'UI_SET_TASKS_SORTING_OPTIONS';
export const UI_SET_TASKS_SHOW_COMPLETED_TASKS = 'UI_SET_TASKS_SHOW_COMPLETED_TASKS';
export const UI_SET_BOOKMARKS_SORTING_OPTIONS = 'UI_SET_BOOKMARKS_SORTING_OPTIONS';

export const FILE_SET_META_DATA = 'FILE_SET_META_DATA';
export const FILE_SET_SAVED = 'FILE_SET_SAVED';
export const FILE_SET_LOADED = 'FILE_SET_LOADED';

export const PROJECT_SET_PROJECT = 'PROJECT_SET_PROJECT';
export const PROJECT_SET_PROJECT_INFO = 'PROJECT_SET_PROJECT_INFO';
export const PROJECT_DELETE_IMAGE = 'PROJECT_DELETE_IMAGE';

export const PROJECT_SET_TASKS = 'PROJECT_SET_TASKS';
export const PROJECT_ADD_TASK = 'PROJECT_ADD_TASK';

export const PROJECT_SET_BOOKMARKS = 'PROJECT_SET_BOOKMARKS';
export const PROJECT_ADD_BOOKMARK = 'PROJECT_ADD_BOOKMARK';
