export const APP_SET_PLATFORM = 'APP_SET_PLATFORM';

export const FILE_SET_META_DATA = 'FILE_SET_META_DATA';
export const FILE_SET_SAVED = 'FILE_SET_SAVED';
export const FILE_SET_LOADED = 'FILE_SET_LOADED';

export const PROJECT_SET_PROJECT_INFO = 'PROJECT_SET_PROJECT_INFO';
